/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns service status and version. Used by load balancers and monitoring.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llms.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * LLMs.txt — machine-readable API description
         * @description Returns a plain-text description of the SFP Entity Formation API for AI agents and LLMs. Follows the llms.txt convention.
         */
        get: operations["llms_txt_llms_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List entity orders
         * @description Paginated list of entity orders with optional filtering.
         */
        get: operations["list_orders_v1_entity_orders_get"];
        put?: never;
        /**
         * Create entity formation order
         * @description Start a new entity formation order. Requires at least one member. Returns the created order with pricing and next required actions.
         */
        post: operations["create_order_v1_entity_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get entity order
         * @description Retrieve a single entity order by ID with next required actions.
         */
        get: operations["get_order_v1_entity_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update entity name
         * @description Update the requested entity name. Only allowed in draft or name_check_failed states.
         */
        patch: operations["update_order_v1_entity_orders__order_id__patch"];
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/intake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete intake
         * @description Mark intake as complete. Transitions draft -> intake_complete. Call this after the order has been created and all member/agent details are finalized.
         */
        post: operations["complete_intake_v1_entity_orders__order_id__intake_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/name-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run name availability check
         * @description Check whether the requested entity name is available in the target jurisdiction. If available, transitions to name_check_passed. If not, transitions to name_check_failed with suggestions.
         */
        post: operations["name_check_v1_entity_orders__order_id__name_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record payment
         * @description Record a successful payment. Transitions name_check_passed -> payment_pending, or payment_pending -> payment_complete. In production, this is triggered by the Stripe webhook.
         */
        post: operations["record_payment_v1_entity_orders__order_id__payment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/human-kernel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create human kernel session
         * @description Create a secure session for the human owner to complete required steps (PII collection, KYC, document signing, attestation). Returns a URL the agent should relay to the human. Transitions order to human_kernel_required.
         */
        post: operations["create_kernel_session_v1_entity_orders__order_id__human_kernel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/documents/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate formation documents
         * @description Generate operating agreement, certificate of formation, and Agent Authority Schedule. Transitions human_kernel_completed -> docs_generated.
         */
        post: operations["generate_documents_v1_entity_orders__order_id__documents_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List order documents
         * @description List all documents generated for an order.
         */
        get: operations["list_documents_v1_entity_orders__order_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/filing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit state filing
         * @description Submit formation documents to the state for filing. Transitions docs_generated -> state_filing_submitted.
         */
        post: operations["submit_filing_v1_entity_orders__order_id__filing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/filing/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm state filing
         * @description Confirm that the state has approved the filing. Transitions state_filing_submitted -> state_confirmed.
         */
        post: operations["confirm_filing_v1_entity_orders__order_id__filing_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/ein": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start EIN application
         * @description Initiate IRS EIN application (Form SS-4) for the formed entity. Transitions state_confirmed -> ein_pending.
         */
        post: operations["apply_ein_v1_entity_orders__order_id__ein_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/ein/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record EIN issuance
         * @description Record that the IRS has issued the EIN. Transitions ein_pending -> ein_issued.
         */
        post: operations["issue_ein_v1_entity_orders__order_id__ein_issue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/bank-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate bank pack
         * @description Generate the bank-pack document bundle for banking introduction. Transitions ein_issued -> bank_pack_ready.
         */
        post: operations["generate_bank_pack_v1_entity_orders__order_id__bank_pack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate entity
         * @description Mark the entity as fully formed and active. Transitions bank_pack_ready -> active.
         */
        post: operations["activate_entity_v1_entity_orders__order_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity-orders/{order_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get audit trail
         * @description Get the audit trail for a specific order, newest first.
         */
        get: operations["get_audit_trail_v1_entity_orders__order_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register webhook
         * @description Register a URL to receive entity status update notifications. Returns the registration with a signing secret for HMAC verification.
         */
        post: operations["register_webhook_v1_webhooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/human/secure/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get kernel session status
         * @description Returns the current status of a human kernel session. Used by the secure form to show which steps are pending.
         */
        get: operations["get_session_status_v1_human_secure__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/human/secure/{token}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a kernel step
         * @description Complete a step in the human kernel flow. On success, advances the session. When all steps complete, the order transitions to human_kernel_completed and a webhook fires.
         */
        post: operations["submit_step_v1_human_secure__token__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/human/secure/{token}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check session completion
         * @description Quick check whether the human owner has completed all required steps.
         */
        get: operations["check_completion_v1_human_secure__token__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionItem
         * @description Describes a single action the caller should (or must) take next.
         */
        ActionItem: {
            /**
             * Action
             * @description Machine-readable action identifier
             */
            action: string;
            /**
             * Endpoint
             * @description API endpoint to call, if applicable
             */
            endpoint?: string | null;
            /**
             * Description
             * @description Human-readable guidance
             */
            description: string;
            /**
             * Required
             * @description Whether this action is mandatory to progress
             */
            required: boolean;
        };
        /**
         * AgentInput
         * @description An AI agent to register as part of the entity structure.
         * @example {
         *       "authority_scope": {
         *         "can_initiate_wires": true,
         *         "can_sign_checks": true,
         *         "max_single_wire_cents": 5000000
         *       },
         *       "display_name": "Treasury Agent v1.2",
         *       "transaction_limit_cents": 10000000
         *     }
         */
        AgentInput: {
            /**
             * Display Name
             * @description Display name for the agent
             */
            display_name: string;
            /**
             * Authority Scope
             * @description JSON object describing what the agent is authorised to do
             */
            authority_scope: {
                [key: string]: unknown;
            };
            /**
             * Transaction Limit Cents
             * @description Per-transaction spending limit in cents
             */
            transaction_limit_cents?: number | null;
        };
        /**
         * AuditEventResponse
         * @description An audit event for the trail endpoint.
         */
        AuditEventResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Ip Address */
            ip_address?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CreateKernelResponse
         * @description Response after creating a human kernel session.
         */
        CreateKernelResponse: {
            /**
             * Kernel Url
             * @description Secure URL for the human owner
             */
            kernel_url: string;
            /**
             * Token Prefix
             * @description First 8 chars of the session token
             */
            token_prefix: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Suggested Message
             * @description Message the agent can relay to the human owner
             */
            suggested_message: string;
        };
        /**
         * CreateOrderRequest
         * @description Payload for ``POST /v1/entity-orders``.
         * @example {
         *       "agent": {
         *         "authority_scope": {
         *           "can_initiate_wires": true,
         *           "can_sign_checks": true
         *         },
         *         "display_name": "Treasury Agent v1.2",
         *         "transaction_limit_cents": 10000000
         *       },
         *       "jurisdiction": "DE",
         *       "members": [
         *         {
         *           "email": "jane@example.com",
         *           "legal_name": "Jane Doe",
         *           "ownership_percentage": 100,
         *           "role": "member"
         *         }
         *       ],
         *       "metadata": {
         *         "campaign": "launch_q1",
         *         "source": "api"
         *       },
         *       "requested_name": "Meridian Autonomous Holdings LLC",
         *       "service_tier": "managed",
         *       "vehicle_type": "llc"
         *     }
         */
        CreateOrderRequest: {
            /**
             * Jurisdiction
             * @description State code, e.g. DE, WY
             */
            jurisdiction: string;
            /**
             * Vehicle Type
             * @description Entity type: llc | dao_llc | corporation
             */
            vehicle_type: string;
            /**
             * Requested Name
             * @description Desired entity name
             */
            requested_name: string;
            /**
             * Service Tier
             * @description Service tier: self_serve | managed | autonomous
             * @default self_serve
             */
            service_tier: string;
            /**
             * Members
             * @description At least one member is required
             */
            members: components["schemas"]["MemberInput"][];
            /** @description Optional AI agent to register */
            agent?: components["schemas"]["AgentInput"] | null;
            /**
             * Metadata
             * @description Arbitrary metadata to store with the order
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CreateWebhookRequest
         * @description Payload for ``POST /v1/webhooks``.
         * @example {
         *       "events": [
         *         "order.state_changed",
         *         "order.completed"
         *       ],
         *       "url": "https://example.com/webhooks/sfp"
         *     }
         */
        CreateWebhookRequest: {
            /**
             * Url
             * Format: uri
             * @description HTTPS URL to receive webhook POST requests
             */
            url: string;
            /**
             * Events
             * @description Event types to subscribe to, e.g. ["order.state_changed", "order.completed", "filing.confirmed"]
             */
            events: string[];
        };
        /**
         * DocumentSummary
         * @description Lightweight document info for list endpoints.
         */
        DocumentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Doc Type */
            doc_type: string;
            /** Template Version */
            template_version: string;
            /** File Hash */
            file_hash: string;
            /** Signing Status */
            signing_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * KernelSessionStatus
         * @description Status of a human kernel session.
         */
        KernelSessionStatus: {
            /**
             * Token Prefix
             * @description First 8 chars of token
             */
            token_prefix: string;
            /**
             * Status
             * @description pending | in_progress | completed | expired
             */
            status: string;
            /** Completed Steps */
            completed_steps: string[];
            /** Remaining Steps */
            remaining_steps: string[];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Is Expired */
            is_expired: boolean;
        };
        /**
         * MemberInput
         * @description A natural person to associate with the entity order.
         * @example {
         *       "email": "jane@example.com",
         *       "legal_name": "Jane Doe",
         *       "ownership_percentage": 50,
         *       "role": "member"
         *     }
         */
        MemberInput: {
            /**
             * Legal Name
             * @description Full legal name
             */
            legal_name: string;
            /**
             * Email
             * @description Contact email
             */
            email?: string | null;
            /**
             * Role
             * @description Role in the entity: member | manager | registered_agent | responsible_party
             * @default member
             */
            role: string;
            /**
             * Ownership Percentage
             * @description Ownership stake as a percentage (0-100)
             */
            ownership_percentage?: number | null;
        };
        /**
         * NameCheckResponse
         * @description Response from name availability check.
         */
        NameCheckResponse: {
            /** Available */
            available: boolean;
            /** Jurisdiction */
            jurisdiction: string;
            /** Entity Name */
            entity_name: string;
            /** Message */
            message: string;
            /** Method */
            method: string;
            /** Suggestions */
            suggestions?: string[];
            transition?: components["schemas"]["StateTransitionResponse"] | null;
        };
        /**
         * OrderListResponse
         * @description Paginated list of orders.
         */
        OrderListResponse: {
            /** Orders */
            orders: components["schemas"]["OrderSummary"][];
            /**
             * Total
             * @description Total matching orders
             */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
        };
        /**
         * OrderResponse
         * @description Canonical representation of an entity order.
         * @example {
         *       "created_at": "2026-02-22T18:00:00Z",
         *       "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
         *       "jurisdiction": "DE",
         *       "next_required_actions": [
         *         {
         *           "action": "complete_intake",
         *           "description": "Submit member/agent details to complete intake",
         *           "endpoint": "POST /v1/entity-orders/a1b2c3d4-e5f6-7890-abcd-ef1234567890/intake",
         *           "required": true
         *         }
         *       ],
         *       "payment_status": "unpaid",
         *       "pricing_cents": 79900,
         *       "requested_name": "Meridian Autonomous Holdings LLC",
         *       "service_tier": "managed",
         *       "state": "draft",
         *       "vehicle_type": "llc"
         *     }
         */
        OrderResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Jurisdiction */
            jurisdiction: string;
            /** Vehicle Type */
            vehicle_type: string;
            /** Requested Name */
            requested_name: string;
            /** Formatted Name */
            formatted_name?: string | null;
            /** State */
            state: string;
            /** Service Tier */
            service_tier: string;
            /** Pricing Cents */
            pricing_cents: number;
            /** Payment Status */
            payment_status: string;
            /**
             * Next Required Actions
             * @description Actions the caller should take to advance the order
             */
            next_required_actions?: components["schemas"]["ActionItem"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * OrderSummary
         * @description Lightweight order representation for list endpoints.
         */
        OrderSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Requested Name */
            requested_name: string;
            /** State */
            state: string;
            /** Jurisdiction */
            jurisdiction: string;
            /** Vehicle Type */
            vehicle_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * StateTransitionResponse
         * @description Response returned after a successful state transition.
         */
        StateTransitionResponse: {
            /** Previous State */
            previous_state: string;
            /** New State */
            new_state: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            order: components["schemas"]["OrderResponse"];
        };
        /**
         * StepResponse
         * @description Response after completing a kernel step.
         */
        StepResponse: {
            /** Step */
            step: string;
            /** Status */
            status: string;
            /** Completed Steps */
            completed_steps: string[];
            /** Remaining Steps */
            remaining_steps: string[];
            /** All Complete */
            all_complete: boolean;
        };
        /**
         * StepSubmission
         * @description Payload for completing a kernel step.
         */
        StepSubmission: {
            /**
             * Step
             * @description Step to complete: pii_collection | kyc_verification | document_signing | attestation
             */
            step: string;
            /**
             * Data
             * @description Step-specific data (e.g., encrypted SSN for pii_collection)
             */
            data?: {
                [key: string]: unknown;
            };
        };
        /**
         * UpdateNameRequest
         * @description Body for PATCH /{order_id} — update the requested entity name.
         */
        UpdateNameRequest: {
            /**
             * Requested Name
             * @description New entity name
             */
            requested_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WebhookResponse
         * @description Representation of a webhook registration.
         * @example {
         *       "active": true,
         *       "created_at": "2026-02-22T18:00:00Z",
         *       "events": [
         *         "order.state_changed",
         *         "order.completed"
         *       ],
         *       "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
         *       "url": "https://example.com/webhooks/sfp"
         *     }
         */
        WebhookResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Url */
            url: string;
            /** Events */
            events: string[];
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    llms_txt_llms_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    list_orders_v1_entity_orders_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                per_page?: number;
                /** @description Filter by jurisdiction code */
                jurisdiction?: string | null;
                /** @description Filter by order state */
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_v1_entity_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_v1_entity_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_order_v1_entity_orders__order_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_intake_v1_entity_orders__order_id__intake_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    name_check_v1_entity_orders__order_id__name_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NameCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_payment_v1_entity_orders__order_id__payment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_kernel_session_v1_entity_orders__order_id__human_kernel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateKernelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_documents_v1_entity_orders__order_id__documents_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v1_entity_orders__order_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_filing_v1_entity_orders__order_id__filing_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_filing_v1_entity_orders__order_id__filing_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_ein_v1_entity_orders__order_id__ein_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_ein_v1_entity_orders__order_id__ein_issue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_bank_pack_v1_entity_orders__order_id__bank_pack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_entity_v1_entity_orders__order_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_trail_v1_entity_orders__order_id__audit_get: {
        parameters: {
            query?: {
                /** @description Max events to return */
                limit?: number;
            };
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_webhook_v1_webhooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_status_v1_human_secure__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KernelSessionStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_step_v1_human_secure__token__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_completion_v1_human_secure__token__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
